resource_group_name    = "kvdemo123244"
location               = "North Europe"
keyvault_name          = "demokv0132143143"
key_permissions = [ "get", ]
secret_permissions = [ "get", "list", "set", "delete" ]
storage_permissions = ["get", ]
virtual_network_subnet_ids=["/subscriptions/029910ea-8f05-405d-a05d-c5550d1d02c0/resourceGroups/Bicep-Demo/providers/Microsoft.Network/virtualNetworks/Bicep-Demo/subnets/default",]
default_action = "Allow"
bypass = "AzureServices"
soft_delete_retention_days= 7