name: test
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    branches:
      - main
      
jobs:
  set-output:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
         token: ${{ secrets.SAML_GITHUB_TOKEN }}
         ref: ${{ github.event.pull_request.head.ref }}       
         repository: ${{ github.event.pull_request.head.repo.full_name }}
